name: firebase_auth_app
description: Example app which uses firebase services

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  result_dart: ^1.1.0
  equatable: ^2.0.5
  get_it: ^7.6.4
  rxdart: ^0.27.7
  cloud_firestore: ^4.13.0
  uuid: ^4.2.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
