import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:rxdart/rxdart.dart';

import '../models/models.dart';
import 'chat_repository.dart';

class CChatRepository implements ChatRepository {
  CChatRepository(this._firestore);
  final FirebaseFirestore _firestore;

  @override
  Future<String> createChannel({
    required String createdByUid,
    required List<String> members,
    required String type,
    String? description,
    String? image,
    String? modifiedAt,
  }) async {
    final result = await _firestore.collection('groups').add({
      'createdBy': createdByUid,
      'type': type,
      'createdAt': Timestamp.now().toString(),
      'description': description,
      'image': image,
      'members': members
    });

    /// TODO:
    /// Create a UID for the channel or update item with autogenerated

    final currentChannelId = result.id;
    await updateChannel(currentChannelId);

    return currentChannelId;
  }

  List<String> getUserIdsFromSnapshot(QuerySnapshot<Object?> snapshot) {
    return snapshot.docs
        .map((doc) => (doc['members'] as List<dynamic>).cast<String>())
        .expand((members) => members)
        .toList();
  }

  @override
  Stream<List<NetworkChannel>> getChannelsByUserId(String id) {
    return _firestore
        .collection('groups')
        .where('createdBy', isEqualTo: id)
        .snapshots()
        .map((response) => response.docs.map((e) => e.data()).toList())
        .switchMap((channels) => Stream.fromFuture(_resolveUsers(channels)))
        .map(NetworkChannel.fromMapList)
        .doOnData(
      (result) {
        print(result.toList().toString());
      },
    );
  }

  @override
  Stream<List<NetworkMessage>> getMessagesByChatId(String id) {
    return _firestore
        .collection('chats')
        .doc(id)
        .collection('messages')
        .orderBy('sentAt')
        .snapshots()
        .map(
      (data) {
        final documents = data.docs;
        return List.from(
          documents.map((e) => NetworkMessage.fromMap(e.data())),
        );
      },
    );
  }

  @override
  Future<void> sendMessage({
    required String channelId,
    required String sentBy,
    required String messageText,
  }) async {
    final payload = {
      'sentBy': sentBy,
      'sentAt': DateTime.timestamp().toString(),
      'messageText': messageText,
    };

    await _firestore
        .collection('chats')
        .doc(channelId)
        .collection('messages')
        .add(payload);
  }

  Future<void> updateChannel(
    String currentId, {
    String? createdByUid,
    List<String>? members,
    String? type,
    String? description,
    String? image,
    String? modifiedAt,
  }) async {
    _firestore.collection('groups').doc(currentId).set({
      'id': currentId,
      'createdBy': createdByUid,
      'type': type,
      'createdAt': Timestamp.now().toString(),
      'description': description,
      'image': image,
      'members': members
    });
  }

  Future<List<Map<String, dynamic>>> _resolveUsers(
    List<Map<String, dynamic>> data,
  ) async {
    List<Map<String, dynamic>> result = [];

    for (var e in data) {
      final users = await _fetchMultipleUsers(e['members']);
      e.update('members', (value) => users);
      result.add(e);
    }

    return result;
  }

  Future<List<Map<String, dynamic>>> _fetchMultipleUsers(
    List<dynamic> ids,
  ) async {
    List<Map<String, dynamic>> result = [];

    for (var id in ids) {
      final response = await _firestore.collection('users').doc(id).get();
      final data = response.data() ?? {};
      result.add(data);
    }

    return result;
  }
}
